config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create]

  delete '/logout' => 'sessions#destroy'
  root "users#index"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	
	validates :name, presence:true
	validates :email, presence: true, uniqueness: {case_insensitive: false}
	
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   helper_method :current_user
  def current_user
  	return @current_user if @current_user
  	if session[:user_id]
  		@current_user = User.find(session[:user_id])
  	end	
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  	if @user = User.find_by(email: params[:email])
  		if @user.authenticate(params[:password])
  			session[:user_id] = @user.id
  			redirect_to root_path, notice: "password not Found"
  		else
  			redirect_to new_session_path, notice: "password not Found"
  		end
  	else
  		redirect_to new_session_path, notice: "User not Found"
  	end
  end
  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, notice: "log Out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		Rails.logger.info request.env["HTTP_COOKIE"]
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.new user_params
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, notice: "Account created."
		else
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav  class="navbar navbar-light"  class="bg-faded">
  	<a class="navbar-brand">CHAT APP</a>
  	<ul class="nav navbar-nav">
  		<% if current_user %>
  		<li class="nav-item">
  			<%= link_to "log out #{current_user.email}", logout_path, method: 'delete',  class: 'nav-link' %>
  		</li>
  		<% else %>
  		<li class="nav-item">
  			<%= link_to "Create An ACcount", new_user_path, class: 'nav-link' %>
  		</li>
  		<li class="nav-item">
  			<%= link_to "Log In", new_session_path, class: 'nav-link' %>
  		</li>
  		<% end %>
  	</ul>
  </nav>
  	<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>User</h1>

<!-- <%= debug @users %> -->
<table class="table">
	<thead class="thead thead-default">
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Created at</th>
		</tr>
	</thead>
	<tbody>
		<%= @users.each do |user| %>
		<tr>
			<td><%= user.name %></td>
			<td><%= user.email %></td>
			<td><%= time_ago_in_words user.created_at %></td>
		</tr>
		<%=	%>
		<% end %>
	</tbody>
</table>	

app/views/users/new.html.erb
<h1>Create an Account</h1>

<%= form_for @user do |f| %>
	<% unless @user.errors.empty? %>
		<alert class="alert-danger">
			<%= @user.errors.full_messages.to_sentence %>
		</alert>
	<% end %>
	
	<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control'%>
	</div>

	<div class="form-group">
	<%= f.label :email %>
	<%= f.text_field :email, class: 'form-control'%>
	</div>

	<div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control'%>
	</div>
	<div class="form-group">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control'%>
	</div>
	<%= f.submit "Create Account", class: 'btn btn-secondary' %>
<% end %>